# Generated by Django 5.0.3 on 2024-03-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_customuser_is_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_vendor',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
