# Generated by Django 5.0.3 on 2024-03-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_alter_customuser_is_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_vendor',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
