# Generated by Django 5.0.3 on 2024-03-29 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_alter_customuser_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinformation',
            name='profile_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
    ]
