# Generated by Django 5.0.3 on 2024-03-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_alter_vendorinformation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinformation',
            name='price',
            field=models.CharField(default='Rs. 0/-', max_length=20),
        ),
    ]
